### ISSUE TITLE
TensorFlow overfitting ?

### ISSUE THREAD

**Issue by AlexpFr** [jomjol/neural-network-digital-counter-readout#10]
I'm not very good at tansorflow but I think I saw you had to be careful with overfitting!
I see you have 400 epochs, isn't that a bit too much?

**Comment by jomjol** [comment]
In principle that could happen. Therefore I first check the convergence with a splitted part for training and evaluation data (parameter can be adjusted in the frist input). If this shows a good convergence, I disable this, to use all data for training.
