### ISSUE TITLE
Water meter digits 7 and 8 wrongly recognized as 0 (white on black)

### ISSUE THREAD

**Issue by RolandRosenfeld** [jomjol/neural-network-digital-counter-readout#11]
First of all I have to say, that AI-on-the-edge is really a great software!
Many thanks for developing this.

I use AI-on-the-edge 7.1.1 with digital counter database dig0900s3q.tflite.
My water meter uses black wheels with white numbers on it, and I observe the problem that the second digit is recognized as 0 (while it should be 8) and the third digit is most of the time recognized as 0 (while it should be 7 or N, because it's between 7 and 8).

Here's a screen shot of the web interface:
![Screenshot of AI-on-the-edge web interface](https://user-images.githubusercontent.com/6381171/121681624-56452800-cabb-11eb-9d0a-5f302549fe7c.png)

I tarred all wrongly detected digits in a tar.gz file:
[tar.gz of the wrongly detected digits](https://github.com/jomjol/neural-network-digital-counter-readout/files/6638091/7and8detectedAs0.tar.gz)

Before upgrading to dig0900s3q.tflite, I used dig0870s3q.tflite with the same problems and today I tried out dig0901s3q.tfline without noting a change.

The analog meters are always recognized correct, so I fear, that the digit database should be trained with white on black digits some more.

Greetings
Roland

**Comment by jomjol** [comment]
I will put the 8 and the 7 to the next training sesssion. 
One remark for future pictures: I only need 1-2 pictures of each number.
