### ISSUE TITLE
Training the model with intermediate stand

### ISSUE THREAD

**Issue by mohammad-karam** [jomjol/neural-network-digital-counter-readout#12]
I am wondering why not detect when the rolling counter is between two digits. why not to have 20 labels"or even more" (0, 0.5 ,1 .... 8.5, 9) instead of 10(0-9). The actual version is detecting it as NaN. 

Thanks

**Comment by jomjol** [comment]
That would be one option. This would increase the size of the neural network quite signifikant (if you would choose 100 outputs). There are other options on the roadmap. Just be a bit patient ;-)
