### ISSUE TITLE
InfluxDB settings will not persist

### ISSUE THREAD

**Issue by mikepflu** [jomjol/neural-network-digital-counter-readout#16]
I am trying to set the InfluxDB settings.  I make sure to check off InfluxDB and all of the fields below it.  I filled in the values, saved the INI file and restarted.  When I check after reboot, the InfluxDB field is unchecked as well as the database.  I am not seeing data in InfluxDB.  I have looked in the logs for any indication that it is trying to write to InfluxDB and I see no errors.  I have also tested the username and password with a curl command and SHOW DATABASES, and this correctly returns the databases.  I believe that I have everything configured properly, so I feel like this could be a bug.

**Comment by jomjol** [comment]
This seems to be a bug. Please enable the MQTT setting manually after the setup in the config.ini directly. I will work on this in one of the next versions.
