### ISSUE TITLE
Digital Green LCD Reading - All Wrong

### ISSUE THREAD

**Issue by jnanadarshan** [jomjol/neural-network-digital-counter-readout#20]
I have a Green LCD screen on my energy meter. The images captured seem to be okay but the readings are all wrong. I see from the Model history that there are quite a few versions trained with LCD Data. I am collecting this LCD data. Can someone help me with how I can train the model only with labeled data from my LCD? Also, how can I pass on the images to jomjol to add it to the overall training data?

![image](https://user-images.githubusercontent.com/16976738/226135381-75ea5b89-63e9-404f-bf6d-f244c7b634bb.png)

**Comment by jomjol** [comment]
This is expected, as this is not part of the training data.
