### ISSUE TITLE
Question to your choosen model

### ISSUE THREAD

**Issue by Schrolli91** [jomjol/neural-network-digital-counter-readout#8]
Hey, i have taken a look at this page:
https://github.com/jomjol/neural-network-digital-counter-readout/blob/master/Train_Network.md

And i asked my, why you use no (None -> linear ??) activation function on the second and third conv-layer?
Is there any reason for that? I have seen a small decrease in accuracy if i run all on relu.

Thanks :-)

**Comment by jomjol** [comment]
Sorry for the late reply, I'm not following this rep-issues frequently. No there is no academical reason. Just try and error
