### ISSUE TITLE
Install Instructions to help me start?

### ISSUE THREAD

**Issue by rgl** [jomjol/neural-network-digital-counter-readout#9]
I want to try out all the Jupyter notebooks that are in this repository but since I never used tensorflow et all, I'm a kinda lost. Can you help me start?

I've installed Jupyter in my Ubuntu 20.04 as:

```bash
python3 -m venv nndcr
cd nndcr
source ./bin/activate
pip install jupyterlab
```

Then started Jupyter as:

```bash
jupyter lab
```

Then in the browser I've opened `Train_CNN_Digital-Readout.ipynb` and tried to execute the first couple of cells which failed because my local installation is missing all the libraries that are in the header of that notebook. Is there a way to install all of these (e.g. maybe a `requirements.txt` file)? Or can you point me to where should I look to install them?

PS I've tried to follow the wiki and your related repositories, but I didn't find any file that seemed to describe this initial setup. The closest thing I found was https://github.com/jomjol/docker-synology-opencv-tensorflow/tree/master/synology, but that seems to only contain binaries, not the recipe to create the container from sources.

**Comment by rgl** [comment]
I've tried to use https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-tensorflow-notebook as:

```bash
docker run --rm -it -p 8888:8888 -v "$PWD:/home/jovyan/work" jupyter/tensorflow-notebook
```

And it seems to work. But "I have no idea what I'm doing" :-)

If this is the way to go, maybe this should be described in this repository README?

**Comment by micky0867** [comment]
Hi,
I'm also new to this but managed somehow to make it work.
I installed jupyter from the Ubuntu repo.
Then installed keras and tensorflow in own conda env.
Then run jupyter in the environment using "jupyter notebook".

**Comment by jomjol** [comment]
Sorry for this late reply. I do not check this repository frequently, because it is rather for documenation.

I do not recommend to use this for getting to know tensorflow and jyupiter.  If I find some time, I might make it a bit more self explaining, but please be patient. It is not going to happen in the next time.
